#
# Warp generated by PBS (Perl Build System) on Wed Dec 10 15:36:38 2008.
# Directory: /devel/perl_modules/PerlBuildSystem/Pbsfiles/config
# User: nadim @ 
# PBS_LIB_PATH: /usr/lib64/perl5/site_perl/5.8.8/PBS/PBSLib/
# Command line: pbs -p parent.pl parent -tno
# PBS Response file: 
# Response file switches: 
# Response file targets : 
#

$global_pbs_config = {
  'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config/out_nadim',
  'SOURCE_DIRECTORIES' => [
    '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config'
  ]
};
$nodes = {
  './parent' => {
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config/out_nadim',
    '__MD5' => 'not built yet',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => '__ROOT',
      'INSERTING_NODE' => '__PBS_warp_tree',
      'INSERTION_FILE' => '3'
    }
  },
  './child' => {
    '__DEPENDENT' => [
      '3'
    ],
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config/out_nadim',
    '__MD5' => 'not built yet',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => '__ROOT',
      'INSERTING_NODE' => './parent',
      'INSERTION_FILE' => '2'
    }
  },
  './grand_daughter' => {
    '__DEPENDED_AT' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config/child.pl',
    '__DEPENDENT' => [
      '2'
    ],
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config/out_nadim',
    '__MD5' => 'not built yet',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => '__ROOT',
      'INSERTING_NODE' => './child',
      'INSERTION_FILE' => '1'
    }
  },
  './grand_son' => {
    '__DEPENDED_AT' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config/child.pl',
    '__DEPENDENT' => [
      '2'
    ],
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config/out_nadim',
    '__MD5' => 'not built yet',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => '__ROOT',
      'INSERTING_NODE' => './child',
      'INSERTION_FILE' => '0'
    }
  },
  './childs_wife' => {
    '__DEPENDENT' => [
      '2'
    ],
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config/out_nadim',
    '__MD5' => 'not built yet',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => '1',
      'INSERTING_NODE' => './child',
      'INSERTION_FILE' => '2'
    }
  }
};

$node_names = [
  './grand_son',
  './grand_daughter',
  './child',
  './parent',
  './childs_wife'
];


$insertion_file_names = [
  '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config/grand_son.pl',
  '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config/grand_daughter.pl',
  '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config/child.pl',
  './parent.pl'
];


$warp_configuration = {
  '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config/grand_daughter.pl' => '389f6e81609daf1819a5d4004434b709',
  '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config/grand_son.pl' => 'd41d8cd98f00b204e9800998ecf8427e',
  '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config/child.pl' => '30f9e48d9153a3d8885c3e56a147bf7d',
  './parent.pl' => '6e98205e8c1418fdba4a5f39a157d3c8'
};


$version = '0.05';
$number_of_nodes_in_the_dependency_tree = 5;


return $nodes, $node_names, $global_pbs_config, $insertion_file_names,
	$version, $number_of_nodes_in_the_dependency_tree, $warp_configuration;