#
# Warp generated by PBS (Perl Build System) on Tue Jun  3 11:02:20 2008.
# Directory: /devel/perl_modules/PerlBuildSystem/Pbsfiles/color
# User: nadim @ 
# PBS_LIB_PATH: /usr/lib64/perl5/site_perl/5.8.8/PBS/PBSLib/
# Command line: pbs all -ndpb
# PBS Response file: 
# Response file switches: 
# Response file targets : 
#

$global_pbs_config = {
  'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/color/out_nadim',
  'SOURCE_DIRECTORIES' => [
    '/devel/perl_modules/PerlBuildSystem/Pbsfiles/color'
  ]
};
$nodes = {
  './all' => {
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/color/out_nadim',
    '__MD5' => 'not built yet',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => '__ROOT',
      'INSERTING_NODE' => '__PBS_warp_tree',
      'INSERTION_FILE' => '0'
    }
  }
};

$node_names = [
  './all'
];


$insertion_file_names = [
  './pbsfile.pl'
];


$warp_configuration = {
  './pbsfile.pl' => 'e44d73d4d9667cdfbf3330482e1f1ea1'
};


$version = '0.05';
$number_of_nodes_in_the_dependency_tree = 1;


return $nodes, $node_names, $global_pbs_config, $insertion_file_names,
	$version, $number_of_nodes_in_the_dependency_tree, $warp_configuration;