#
# Warp generated by PBS (Perl Build System) on Wed Feb 25 17:13:34 2009.
# Directory: /devel/perl_modules/PerlBuildSystem/Pbsfiles/hello
# User: nadim @ 
# PBS_LIB_PATH: /usr/lib64/perl5/site_perl/5.8.8/PBS/PBSLib/
# Command line: pbs 
# PBS Response file: 
# Response file switches: 
# Response file targets : 
#

$global_pbs_config = {
  'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello/out_nadim',
  'SOURCE_DIRECTORIES' => [
    '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
  ]
};
$nodes = {
  './world.o' => {
    '__DEPENDENT' => [
      '1'
    ],
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello/out_nadim',
    '__MD5' => '14065be6ebdc96abbcc397bfe1bafca0',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'a.out',
      'INSERTING_NODE' => './a.out',
      'INSERTION_FILE' => '0'
    }
  },
  '/usr/include/libio.h' => {
    '__DEPENDENT' => [
      '5'
    ],
    '__MD5' => 'e2b0512073f798cf9933ea5b7cc8234b',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/stdio.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/wchar.h' => {
    '__DEPENDENT' => [
      '15'
    ],
    '__MD5' => '8ea378ba27d5e925c38dfab032726f16',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/_G_config.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/bits/stdio_lim.h' => {
    '__DEPENDENT' => [
      '5'
    ],
    '__MD5' => 'bc8b1b1d13e5e69133f85c645f7e2a06',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/stdio.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  './all' => {
    '__MD5' => 'VIRTUAL',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => '__ROOT',
      'INSERTING_NODE' => '__PBS_root_NEEDS_REBUILD_pbs_._Pbsfile.pl',
      'INSERTION_FILE' => '0'
    },
    '__VIRTUAL' => 1
  },
  '/usr/include/sys/types.h' => {
    '__DEPENDENT' => [
      '21'
    ],
    '__MD5' => 'ac5b3da3ea53cf7141c907159c436822',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/stdlib.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  './main.o' => {
    '__DEPENDENT' => [
      '1'
    ],
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello/out_nadim',
    '__MD5' => 'b6bda14b1b0b521f1783903b34ac1584',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'a.out',
      'INSERTING_NODE' => './a.out',
      'INSERTION_FILE' => '0'
    }
  },
  '/usr/include/features.h' => {
    '__DEPENDENT' => [
      '5'
    ],
    '__MD5' => 'e4afe07f5c096f823c4808a2500a003e',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/stdio.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/bits/pthreadtypes.h' => {
    '__DEPENDENT' => [
      '22'
    ],
    '__MD5' => '66624b434da8e2e8850685cc60d5c77f',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/sys/types.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/bits/types.h' => {
    '__DEPENDENT' => [
      '5'
    ],
    '__MD5' => '4d4d4224ed1a8e7740eb337703df2f2b',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/stdio.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/sys/select.h' => {
    '__DEPENDENT' => [
      '22'
    ],
    '__MD5' => '3ac38d7e2f9203f1343788fe7a736c4d',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/sys/types.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/stdio.h' => {
    '__DEPENDENT' => [
      '4',
      '34'
    ],
    '__MD5' => '0e75dd6069bb195aa5a7b9288a8ddf15',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello/main.c',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  './main.c' => {
    '__DEPENDENT' => [
      '2'
    ],
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
    '__MD5' => '7229c982ea0c55ae6d335c357ed8d2dd',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'o_cs_meta',
      'INSERTING_NODE' => './main.o',
      'INSERTION_FILE' => '0'
    }
  },
  '/usr/lib/gcc/x86_64-pc-linux-gnu/4.1.2/include/stdarg.h' => {
    '__DEPENDENT' => [
      '14'
    ],
    '__MD5' => '10c9f28806d14aba38914b97ca1ba7d1',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/libio.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/alloca.h' => {
    '__DEPENDENT' => [
      '21'
    ],
    '__MD5' => '2cd6c8d99645ffaa331ba97e071bca67',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/stdlib.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/stdlib.h' => {
    '__DEPENDENT' => [
      '4',
      '34'
    ],
    '__MD5' => '6e33299bc7091a4e4db456c2b0723ead',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello/main.c',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  './a.out' => {
    '__DEPENDENT' => [
      '0'
    ],
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello/out_nadim',
    '__MD5' => '7c1d670b4893ded837c74c560710274c',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'all',
      'INSERTING_NODE' => './all',
      'INSERTION_FILE' => '0'
    }
  },
  '/usr/include/bits/sigset.h' => {
    '__DEPENDENT' => [
      '27'
    ],
    '__MD5' => '621a88e81f6a381d97852e76bf05ef79',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/sys/select.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello/common.h' => {
    '__DEPENDENT' => [
      '4',
      '34'
    ],
    '__MD5' => '43c5fc3081d06083c311c26a176c6dc6',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello/main.c',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/bits/time.h' => {
    '__DEPENDENT' => [
      '27'
    ],
    '__MD5' => '39b0c941e291970324de2709f164c3be',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/sys/select.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/bits/sys_errlist.h' => {
    '__DEPENDENT' => [
      '5'
    ],
    '__MD5' => 'e7734f693e8e68fcc97d98e790d024a1',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/stdio.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/lib/gcc/x86_64-pc-linux-gnu/4.1.2/include/stddef.h' => {
    '__DEPENDENT' => [
      '5',
      '15',
      '21',
      '22',
      '33'
    ],
    '__MD5' => 'd3997415756a38f21512282ded1ade20',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/stdio.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/sys/cdefs.h' => {
    '__DEPENDENT' => [
      '6'
    ],
    '__MD5' => '3ce9d860555db167d2a6ca018749d80f',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/features.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/gnu/stubs.h' => {
    '__DEPENDENT' => [
      '6'
    ],
    '__MD5' => '326ea516d2af549d9de3f71532c4e4e4',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/features.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/bits/wordsize.h' => {
    '__DEPENDENT' => [
      '7',
      '9',
      '12',
      '26',
      '32'
    ],
    '__MD5' => '30529eb770bdf401a7dc82c1659f4364',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/sys/cdefs.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/time.h' => {
    '__DEPENDENT' => [
      '22',
      '27'
    ],
    '__MD5' => 'a701f3f77dc321259da9e5945328f3c5',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/sys/types.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/endian.h' => {
    '__DEPENDENT' => [
      '22'
    ],
    '__MD5' => '566f63c5e01d31f43f69b295daa32dd7',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/sys/types.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/_G_config.h' => {
    '__DEPENDENT' => [
      '14'
    ],
    '__MD5' => 'ef82adb9801d9d9e111d0104c1a0b47e',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/libio.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/sys/sysmacros.h' => {
    '__DEPENDENT' => [
      '22'
    ],
    '__MD5' => 'c593bd20ffb2a01c6192dacee4acf2a9',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/sys/types.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/bits/endian.h' => {
    '__DEPENDENT' => [
      '24'
    ],
    '__MD5' => '93f54525ca894fe9c4f79236cd9b8bf3',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/endian.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/gnu/stubs-64.h' => {
    '__DEPENDENT' => [
      '9'
    ],
    '__MD5' => '586c5440879912c71a45e8b57e833d89',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/gnu/stubs.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/bits/typesizes.h' => {
    '__DEPENDENT' => [
      '12'
    ],
    '__MD5' => 'af928b23500851e2da8cd3ec56d56edf',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/bits/types.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/bits/byteswap.h' => {
    '__DEPENDENT' => [
      '24'
    ],
    '__MD5' => 'f5d9de88196821f8268b3ace5cbd178e',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/endian.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  '/usr/include/bits/select.h' => {
    '__DEPENDENT' => [
      '27'
    ],
    '__MD5' => 'bb161dc5a7b233a76c3ac3c389cef8d8',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/usr/include/sys/select.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello'
      ]
    }
  },
  './world.c' => {
    '__DEPENDENT' => [
      '3'
    ],
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello',
    '__MD5' => '78978c414b25e11d9c556dbebb2bad68',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'o_cs_meta',
      'INSERTING_NODE' => './world.o',
      'INSERTION_FILE' => '0'
    }
  }
};

$node_names = [
  './all',
  './a.out',
  './main.o',
  './world.o',
  './main.c',
  '/usr/include/stdio.h',
  '/usr/include/features.h',
  '/usr/include/sys/cdefs.h',
  '/usr/include/bits/wordsize.h',
  '/usr/include/gnu/stubs.h',
  '/usr/include/gnu/stubs-64.h',
  '/usr/lib/gcc/x86_64-pc-linux-gnu/4.1.2/include/stddef.h',
  '/usr/include/bits/types.h',
  '/usr/include/bits/typesizes.h',
  '/usr/include/libio.h',
  '/usr/include/_G_config.h',
  '/usr/include/wchar.h',
  '/usr/lib/gcc/x86_64-pc-linux-gnu/4.1.2/include/stdarg.h',
  '/usr/include/bits/stdio_lim.h',
  '/usr/include/bits/sys_errlist.h',
  '/devel/perl_modules/PerlBuildSystem/Pbsfiles/hello/common.h',
  '/usr/include/stdlib.h',
  '/usr/include/sys/types.h',
  '/usr/include/time.h',
  '/usr/include/endian.h',
  '/usr/include/bits/endian.h',
  '/usr/include/bits/byteswap.h',
  '/usr/include/sys/select.h',
  '/usr/include/bits/select.h',
  '/usr/include/bits/sigset.h',
  '/usr/include/bits/time.h',
  '/usr/include/sys/sysmacros.h',
  '/usr/include/bits/pthreadtypes.h',
  '/usr/include/alloca.h',
  './world.c'
];


$insertion_file_names = [
  './Pbsfile.pl',
  '__C_DEPENDER'
];


$warp_configuration = {
  '/usr/lib64/perl5/site_perl/5.8.8/PBS/PBSLib/Configs/Compilers/gcc.pm' => '02d564a7fc3342d131da9212863d0c08',
  '/usr/lib64/perl5/site_perl/5.8.8/PBS/PBSLib/Rules/C_depender.pm' => '71e1f2cd4ddf78bcc6e912f09da42a66',
  '/usr/lib64/perl5/site_perl/5.8.8/PBS/PBSLib/MetaRules/FirstAndOnlyOneOnDisk.pm' => '6d62d4df04b63577e01d5ae8b88d8b4f',
  '/usr/lib64/perl5/site_perl/5.8.8/PBS/PBSLib/Rules/C.pm' => 'e3c5b1657bf8edc9fd00d5d6eff22414',
  './Pbsfile.pl' => 'f0a120f52dc15f5cf0dafc7332944571'
};


$version = '0.05';
$number_of_nodes_in_the_dependency_tree = 35;


return $nodes, $node_names, $global_pbs_config, $insertion_file_names,
	$version, $number_of_nodes_in_the_dependency_tree, $warp_configuration;