	
	# version module automatically generated by the build system
	
	package PBS::Version ;
	
	sub GetVersion {return '0.45.56'} ;
	
	# generated from commit 7172b7b994723de94bf508b2dc03dfb3c134550b
	
	1 ;
	
	# end of generated version module
