	
	# version module automatically generated by the build system
	
	package PBS::Version ;
	
	sub GetVersion {return '0.45.52'} ;
	
	# generated from commit 35c3876b912f45260bea82a2b1eae8947fc499af
	
	1 ;
	
	# end of generated version module
