	
	# version module automatically generated by the build system
	
	package PBS::Version ;
	
	sub GetVersion {return '0.45.48'} ;
	
	# generated from commit 06abc846219b9b2228b9df547d30a17b6dae7bbb
	
	1 ;
	
	# end of generated version module
