#
# Warp generated by PBS (Perl Build System) on Fri May 23 11:10:31 2008.
# Directory: /devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic
# User: nadim @ 
# PBS_LIB_PATH: /usr/lib64/perl5/site_perl/5.8.8/PBS/PBSLib/
# Command line: pbs 
# PBS Response file: 
# Response file switches: 
# Response file targets : 
#

$global_pbs_config = {
  'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic/out_nadim',
  'SOURCE_DIRECTORIES' => [
    '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic'
  ]
};
$nodes = {
  './cyclic_test' => {
    '__DEPENDENT' => [
      '0'
    ],
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic/out_nadim',
    '__MD5' => 'not built yet',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'all',
      'INSERTING_NODE' => './all',
      'INSERTION_FILE' => '0'
    }
  },
  '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic/b.h' => {
    '__DEPENDENT' => [
      '4',
      '5'
    ],
    '__MD5' => 'ee1331734f08211e81c61b6a69305104',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic/a.h',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic'
      ]
    }
  },
  '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic/a.h' => {
    '__DEPENDENT' => [
      '3',
      '6'
    ],
    '__MD5' => '8370553e6c1d4a9e30aa075d6a7ce082',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'NO_CACHE',
      'INSERTING_NODE' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic/a.c',
      'INSERTION_FILE' => '1'
    },
    '__PBS_CONFIG' => {
      'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic',
      'SOURCE_DIRECTORIES' => [
        '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic'
      ]
    }
  },
  './a.c' => {
    '__DEPENDENT' => [
      '2'
    ],
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic',
    '__MD5' => '22c996360c847ae643c34bfb37de3835',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'objects',
      'INSERTING_NODE' => './cyclic_test.objects',
      'INSERTION_FILE' => '0'
    }
  },
  './cyclic_test.objects' => {
    '__DEPENDENT' => [
      '1'
    ],
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic/out_nadim',
    '__MD5' => '3f4f1bb3f4afe52507676895d49a2c1c',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'cyclic_test',
      'INSERTING_NODE' => './cyclic_test',
      'INSERTION_FILE' => '0'
    }
  },
  './all' => {
    '__MD5' => 'not built yet',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => '__ROOT',
      'INSERTING_NODE' => '__PBS_root_NEEDS_REBUILD_pbs_._Pbsfile.pl',
      'INSERTION_FILE' => '0'
    },
    '__VIRTUAL' => 1
  },
  './b.c' => {
    '__DEPENDENT' => [
      '2'
    ],
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic',
    '__MD5' => '9bd238335d592b0c1f90d7ad4ac8450b',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'objects',
      'INSERTING_NODE' => './cyclic_test.objects',
      'INSERTION_FILE' => '0'
    }
  }
};

$node_names = [
  './all',
  './cyclic_test',
  './cyclic_test.objects',
  './a.c',
  './b.c',
  '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic/a.h',
  '/devel/perl_modules/PerlBuildSystem/Pbsfiles/cyclic/b.h'
];


$insertion_file_names = [
  './Pbsfile.pl',
  '__C_DEPENDER'
];


$warp_configuration = {
  '/usr/lib64/perl5/site_perl/5.8.8/PBS/PBSLib/Configs/Compilers/gcc.pm' => '02d564a7fc3342d131da9212863d0c08',
  '/usr/lib64/perl5/site_perl/5.8.8/PBS/PBSLib/Rules/C_depender.pm' => '71e1f2cd4ddf78bcc6e912f09da42a66',
  '/usr/lib64/perl5/site_perl/5.8.8/PBS/PBSLib/MetaRules/FirstAndOnlyOneOnDisk.pm' => '6d62d4df04b63577e01d5ae8b88d8b4f',
  '/usr/lib64/perl5/site_perl/5.8.8/PBS/PBSLib/Rules/C.pm' => 'e3c5b1657bf8edc9fd00d5d6eff22414',
  './Pbsfile.pl' => 'a14ee2fe41a771f45a85993e2061353f',
  '/usr/lib64/perl5/site_perl/5.8.8/PBS/PBSLib/Builders/Objects.pm' => 'bc0bdf6ff8ce2f1ed642d945f316f59b'
};


$version = '0.05';
$number_of_nodes_in_the_dependency_tree = 7;


return $nodes, $node_names, $global_pbs_config, $insertion_file_names,
	$version, $number_of_nodes_in_the_dependency_tree, $warp_configuration;