#
# Warp generated by PBS (Perl Build System) on Fri Sep 18 08:20:51 2009.
# Directory: /devel/perl_modules/PerlBuildSystem/Pbsfiles/config_dependency
# User: nadim @ 
# PBS_LIB_PATH: ./
# Command line: pbs -plp . -p test.pl generated
# PBS Response file: 
# Response file switches: 
# Response file targets : 
#

$global_pbs_config = {
  'BUILD_DIRECTORY' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config_dependency/out_nadim',
  'SOURCE_DIRECTORIES' => [
    '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config_dependency'
  ]
};
$nodes = {
  './generated_config_and_filter_cache' => {
    '__DEPENDENT' => [
      '0'
    ],
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config_dependency/out_nadim',
    '__MD5' => '4f7413f07b7dee14151a6bd1a5c55a55',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'generated',
      'INSERTING_NODE' => './generated',
      'INSERTION_FILE' => '0'
    }
  },
  './generated' => {
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config_dependency/out_nadim',
    '__MD5' => 'd41d8cd98f00b204e9800998ecf8427e',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => '__ROOT',
      'INSERTING_NODE' => '__PBS_root_NEEDS_REBUILD_pbs_._test.pl',
      'INSERTION_FILE' => '0'
    }
  },
  './filter' => {
    '__DEPENDENT' => [
      '1'
    ],
    '__LOCATION' => '/devel/perl_modules/PerlBuildSystem/Pbsfiles/config_dependency',
    '__MD5' => 'c3b0c92cc0da1fb2dcffcdba1ca6ae2c',
    '__INSERTED_AT' => {
      'INSERTION_RULE' => 'generated_config_and_filter_cache',
      'INSERTING_NODE' => './generated_config_and_filter_cache',
      'INSERTION_FILE' => '0'
    }
  }
};

$node_names = [
  './generated',
  './generated_config_and_filter_cache',
  './filter'
];


$insertion_file_names = [
  './test.pl'
];


$warp_configuration = {
  './config_dependent.pm' => '5ac76738c6bd92584cca2f5fca67ef05',
  './test.pl' => '09ad28d0441d39eb20110535152c7e3e'
};


$version = '0.05';
$number_of_nodes_in_the_dependency_tree = 3;


return $nodes, $node_names, $global_pbs_config, $insertion_file_names,
	$version, $number_of_nodes_in_the_dependency_tree, $warp_configuration;